### ISSUE TITLE
64 bit upgrade to support macOS Catalina 10.15?

### ISSUE THREAD

**Issue by billagee4** [bslabs/anypiamac#1]
I found this a few months ago and it's very helpful for Mac users so thanks for your hard work and ongoing table updates.  However I see that it will be broken when upgrading to the latest macOS 10.15 which only permits 64 bit apps.  Is it possible to convert the app to 64 bit?  Thanks!

Bill

**Comment by mrpippy** [comment]
No, the app will need a full rewrite to run on 10.15 (which is not likely to happen). Running the Windows version using Wine (once that is fully 10.15-ready) is probably the next best solution.

**Comment by billagee4** [comment]
Thanks!
